[project]
name = "sheets2anki"
version = "1.0.0"
requires-python = ">=3.9"

[tool.ruff]
exclude = ["remote_decks/libs/**"]

[tool.mypy]
module = [
  "sheets2anki.remote_decks.libs.*",
]
exclude = "remote_decks/libs/"
follow_imports = "skip"

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "aqt",
    "mypy",
    "pre-commit",
    "pytest",
    "ruff",
    "types-requests",
]
